name: 🚀 Deploy ClipSmart to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Go to home
          cd /home/ubuntu

          # Clone or pull repo
          if [ ! -d "clipsmart-public" ]; then
            git clone https://github.com/ujjwalm9895/clipsmart-public.git
          fi
          cd clipsmart-public
          git pull origin master

          # Create .env file in backend folder
          cd backend
          cat <<EOF > .env
PORT=${{ secrets.PORT }}
AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
AWS_REGION=${{ secrets.AWS_REGION }}
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
FLASK_ENV=${{ secrets.FLASK_ENV }}
FLASK_PORT=${{ secrets.FLASK_PORT }}
FLASK_HOST=${{ secrets.FLASK_HOST }}
PROXY_USERNAME=${{ secrets.PROXY_USERNAME }}
PROXY_PASSWORD=${{ secrets.PROXY_PASSWORD }}
YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
WEBSHARE_USERNAME=${{ secrets.WEBSHARE_USERNAME }}
WEBSHARE_PASSWORD=${{ secrets.WEBSHARE_PASSWORD }}
EOF
          cd ..

          # Run docker compose
          docker compose down || true
          docker compose build
          docker compose up -d

          # Optional: cleanup
          docker system prune -f || true
