name: clipsmart-be-main

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: [ClipSmart-ujjwal]

    steps:
      - name: Clone or Pull Repo on EC2
        run: |
          cd ~
          if [ -d "clipsmart-public" ]; then
            cd clipsmart-public && git pull origin master
          else
            git clone https://github.com/ujjwalm9895/clipsmart-public.git
            cd clipsmart-public
          fi

      - name: Create .env file in backend
        run: |
          cd ~/clipsmart-public/backend
          cat <<EOF > .env
PORT=${{ secrets.PORT }}
AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
AWS_REGION=${{ secrets.AWS_REGION }}
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
FLASK_ENV=${{ secrets.FLASK_ENV }}
FLASK_PORT=${{ secrets.FLASK_PORT }}
FLASK_HOST=${{ secrets.FLASK_HOST }}
PROXY_USERNAME=${{ secrets.PROXY_USERNAME }}
PROXY_PASSWORD=${{ secrets.PROXY_PASSWORD }}
YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
WEBSHARE_USERNAME=${{ secrets.WEBSHARE_USERNAME }}
WEBSHARE_PASSWORD=${{ secrets.WEBSHARE_PASSWORD }}
EOF

      - name: Docker Compose Build & Deploy
        run: |
          cd ~/clipsmart-public
          docker compose down || true
          docker compose build
          docker compose up -d

      - name: Docker Cleanup
        run: docker system prune -f
